NodeURL:
  - 'https://testnet.era.zksync.dev'
GraphClientPoolSize: 10
HttpPoolSize: 10
APIDelayTime: 60
EmailCodeExpireTime: 60
FTDepositWithdrawRedisLockTime: 30
KeyExpireTime: 1800
KeyNoExpireTime: 604800
MarketplaceContract: '0x84C765E6E885c53d179511FCFA459519B8fDF908'
MarketplaceGraph: 'https://api.thegraph.com/subgraphs/name/connectorgamefi/connextion_market_test'
GameLootEquipmentGraph: 'http://34.80.207.160:8000/subgraphs/name/zksync/nft_test'
BlindBoxImage: 'https://ipfs.io/ipfs/QmcKYNetqdWnbec4QzMN9fY8VkY4fshRSdrXtfkytTYCSG'
GameEquipmentName: ArchLootPart
AdminNodeURL: 'https://open.larksuite.com/open-apis/bot/v2/hook/2aa09250-09bc-46d0-85f4-38e924b5fe51'

GameConfig:

SignConfig:
  SignaturePublicFile: ./pub.pem
  SignServerURL: 'http://34.81.246.151:8085'
  SignResultServerURL: 'http://34.81.246.151:8086'
  SignRequestNum: 100
HTTPSConfig:
  CertFile: ./cert.pem
  KeyFile: ./key.pem
ServerConfig:
  RunMode: info
  HttpPort: '8888'
  ReadTimeout: 0
  WriteTimeout: 0
  JWTExpireTimeMinute: 43200
  JWTSecret: connexion.games
  TLSCAFile: ./test.pem
  TLSCAKey: ./test.key
  LogOut: stdout
MysqlConfig:
  UseCA: false
  IP: 34.81.246.199
  SSHPort: 22
  SSHAccount: ''
  SSHKey: ''
  ConnPort: 3306
  Account: root
  Password: Eqvt!g93GL
  SqlName: connexionSDK
  MaxOpenConns: 100
  MaxIdleConns: 20
  MaxLifetime: 3600
RedisConfig:
  UseCA: false
  IP: ''
  SSHPort: 22
  SSHAccount: ''
  SSHKey: ''
  Name: ''
  Password: 9o-^dBTLN!
  Host: '34.81.246.199:6379'
  DB: 0
  MinIdleConns: 20
MiddlewareLogConfig:
  VisitLogFile: /Users/btcex88/gopath/src/github/ConnexionSDK/cmd/log/visit.log
  RecoverLogFile: /Users/btcex88/gopath/src/github/ConnexionSDK/cmd/log/recover.log
  SkipPath: []
NetworkChain:
  bsc-test: 97
  rinkeby: 4
  ethereum: 1
  bsc: 56
  zk-test: 280
ChainToken:
  '1':
    TokenName: ETH
    Decimal: 18
  '4':
    TokenName: ETH
    Decimal: 18
  '56':
    TokenName: BNB
    Decimal: 18
  '97':
    TokenName: BNB
    Decimal: 18
  '280':
    TokenName: ZKT
    Decimal: 18
SkyWalkingConfig:
  ServerName: gosdk-test
  SkyRPCNode: '192.168.6.5:11800'
  KeyGameWithdraw: gameWithdraw
  KeyRiskReview: riskReview
  KeyWithdraw: withdraw
  ValueGameWithdraw: gameserver/withdraw
  ValueRiskReview: adminserver/riskReview
  ValueWithdraw: dashboard/prewithdraw
AssetSortConfig: '{"ArchLootPart":10,"BOSSChest":9,"CommonChest":8,"RepairingPotion":7}'
PassAssetConfig: '{"AdventurerPass":"26092","CollectorPass":"26093","GoblinPass":"26090"}'
